import {
  ADVISOR_DRILLDOWN_DEFAULT_LIMIT,
  ADVISOR_DRILLDOWN_MAX_LIMIT,
} from '../advisor-cash-realized-breakdown.js';
import type {
  AnalyticalDimensionKey,
  AnalyticalDirection,
  AnalyticalExecutorKey,
  AnalyticalFilterKey,
  AnalyticalMetricKey,
  AnalyticalOperationKey,
  AnalyticalPeriodKind,
  AnalyticalPartyProfile,
  AnalyticalSemanticFamily,
} from './analytical-keys.js';

/**
 * Capability Registry = capacidades PUBLICADAS/homologadas hoje.
 * Deny by default: engine teórico ≠ capability publicada.
 * Capability publicada não significa resultado AVAILABLE: o quality gate decide.
 * Não publicar YTD/YEAR de centro de custo, bank, forecast ou competence universais.
 */
export type AnalyticalCapability = {
  readonly key: string;
  readonly metric: AnalyticalMetricKey;
  readonly semanticFamily: AnalyticalSemanticFamily;
  /**
   * null = direction deve estar ausente.
   * Array = direction obrigatória e ∈ lista.
   */
  readonly directions: readonly AnalyticalDirection[] | null;
  /**
   * Inclui `null` quando a capability é agregação sem dimensão.
   */
  readonly dimensions: readonly (AnalyticalDimensionKey | null)[];
  readonly periodKinds: readonly AnalyticalPeriodKind[];
  /** Para COMPARISON: kinds permitidos em left/right. */
  readonly comparisonChildKinds: readonly AnalyticalPeriodKind[] | null;
  readonly operations: readonly AnalyticalOperationKey[];
  readonly allowedFilters: readonly AnalyticalFilterKey[];
  /** Filters que devem estar presentes (não vazios). */
  readonly requiredFilters: readonly AnalyticalFilterKey[];
  /**
   * Quando definido, o valor de filters.partyProfile precisa ser exatamente este.
   * A chave sozinha não autoriza CUSTOMER e SUPPLIER ao mesmo tempo.
   */
  readonly requiredPartyProfile?: AnalyticalPartyProfile;
  readonly identityRequired: boolean;
  readonly maxLimit: number | null;
  readonly defaultLimit: number | null;
  readonly executorKey: AnalyticalExecutorKey;
  readonly sourceToolOrSurface: string;
};

const DRILL_MAX = ADVISOR_DRILLDOWN_MAX_LIMIT;
const DRILL_DEFAULT = ADVISOR_DRILLDOWN_DEFAULT_LIMIT;

export const ANALYTICAL_CAPABILITY_REGISTRY: readonly AnalyticalCapability[] = [
  // --- compare_cash_months ---
  {
    key: 'billing.compare.month_pair',
    metric: 'BILLING',
    semanticFamily: 'BILLING',
    directions: null,
    dimensions: [null],
    periodKinds: ['COMPARISON'],
    comparisonChildKinds: ['MONTH'],
    operations: ['COMPARE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'compareCashMonths',
    sourceToolOrSurface: 'compare_cash_months',
  },
  {
    key: 'realized_cash.compare.month_pair.totals',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: [null],
    periodKinds: ['COMPARISON'],
    comparisonChildKinds: ['MONTH'],
    operations: ['COMPARE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'compareCashMonths',
    sourceToolOrSurface: 'compare_cash_months',
  },
  {
    key: 'cash_result.compare.month_pair',
    metric: 'CASH_RESULT',
    semanticFamily: 'FLOW',
    directions: ['NET'],
    dimensions: [null],
    periodKinds: ['COMPARISON'],
    comparisonChildKinds: ['MONTH'],
    operations: ['COMPARE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'compareCashMonths',
    sourceToolOrSurface: 'compare_cash_months',
  },
  {
    key: 'realized_cash.compare.month_pair.category',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['CATEGORY'],
    periodKinds: ['COMPARISON'],
    comparisonChildKinds: ['MONTH'],
    operations: ['COMPARE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'compareCashMonths',
    sourceToolOrSurface: 'compare_cash_months',
  },

  // --- FINANCIAL_FACTS preload (mês civil) ---
  {
    key: 'billing.value.month',
    metric: 'BILLING',
    semanticFamily: 'BILLING',
    directions: null,
    dimensions: [null],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'financialFactsMonth',
    sourceToolOrSurface: 'FINANCIAL_FACTS',
  },
  {
    key: 'billing.series.months',
    metric: 'BILLING',
    semanticFamily: 'BILLING',
    directions: null,
    dimensions: [null],
    periodKinds: ['MONTH_WINDOW'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'billingSeriesMonths',
    sourceToolOrSurface: 'FINANCIAL_FACTS',
  },
  {
    key: 'realized_cash.value.month',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: [null],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'financialFactsMonth',
    sourceToolOrSurface: 'FINANCIAL_FACTS',
  },
  {
    key: 'cash_result.value.month',
    metric: 'CASH_RESULT',
    semanticFamily: 'FLOW',
    directions: ['NET'],
    dimensions: [null],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'financialFactsMonth',
    sourceToolOrSurface: 'FINANCIAL_FACTS',
  },

  // --- planejamento mensal consolidado (meta e teto) ---
  {
    key: 'revenue_goal.value.month',
    metric: 'REVENUE_GOAL',
    semanticFamily: 'PLANNING',
    directions: null,
    dimensions: [null],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'monthlyPlanning',
    sourceToolOrSurface: 'monthly_planning',
  },
  {
    key: 'expense_ceiling.value.month',
    metric: 'EXPENSE_CEILING',
    semanticFamily: 'PLANNING',
    directions: null,
    dimensions: [null],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'monthlyPlanning',
    sourceToolOrSurface: 'monthly_planning',
  },

  // --- cash_realized_breakdown ---
  {
    key: 'realized_cash.category.month.breakdown',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['CATEGORY'],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['BREAKDOWN'],
    allowedFilters: ['costCenterQuery'],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCategoryBreakdown',
    sourceToolOrSurface: 'cash_realized_breakdown',
  },

  // --- cash_movement_lines ---
  {
    key: 'realized_cash.movements.month',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: [null],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['MOVEMENTS'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashMovements',
    sourceToolOrSurface: 'cash_movement_lines',
  },

  // Movimentos realizados de um dia civil. Mesma semântica do ponto diário da Home.
  {
    key: 'realized_cash.day.movements',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: [null],
    periodKinds: ['DAY'],
    comparisonChildKinds: null,
    operations: ['MOVEMENTS'],
    allowedFilters: ['costCenterQuery'],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashDayMovements',
    sourceToolOrSurface: 'cash_realized_day_movements',
  },

  // --- cash_nominal_dimension_* (INFLOW only, published) ---
  {
    key: 'realized_cash.counterparty.inflow.ranking_winner',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['RANKING_WINNER'],
    allowedFilters: ['categoryReference'],
    requiredFilters: ['categoryReference'],
    identityRequired: false,
    maxLimit: 1,
    defaultLimit: 1,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'cash_nominal_dimension_ranking',
  },
  {
    key: 'realized_cash.counterparty.inflow.ranking_topn',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['RANKING_TOPN'],
    allowedFilters: ['categoryReference'],
    requiredFilters: ['categoryReference'],
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'cash_nominal_dimension_ranking',
  },
  {
    key: 'realized_cash.counterparty.inflow.lookup',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['LOOKUP'],
    allowedFilters: ['categoryReference'],
    requiredFilters: [],
    identityRequired: true,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'cash_nominal_dimension_lookup',
  },
  {
    key: 'realized_cash.counterparty.inflow.compare.month_pair',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['COMPARISON'],
    comparisonChildKinds: ['MONTH'],
    operations: ['COMPARE'],
    allowedFilters: ['categoryReference'],
    requiredFilters: [],
    // entityQuery/identity é opcional no tool atual (compare de população ou entidade).
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'compare_cash_nominal_dimension',
  },

  // --- counterparty por partyProfile (quality gate decide AVAILABLE/PARTIAL/UNAVAILABLE) ---
  {
    key: 'realized_cash.counterparty.inflow.customer.ranking_winner',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['RANKING_WINNER'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'CUSTOMER',
    identityRequired: false,
    maxLimit: 1,
    defaultLimit: 1,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.outflow.supplier.ranking_winner',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['OUTFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['RANKING_WINNER'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'SUPPLIER',
    identityRequired: false,
    maxLimit: 1,
    defaultLimit: 1,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.inflow.customer.ranking_topn',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['RANKING_TOPN'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'CUSTOMER',
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.outflow.supplier.ranking_topn',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['OUTFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['RANKING_TOPN'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'SUPPLIER',
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.inflow.customer.lookup',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['LOOKUP'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'CUSTOMER',
    identityRequired: true,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.outflow.supplier.lookup',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['OUTFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['LOOKUP'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'SUPPLIER',
    identityRequired: true,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.inflow.customer.share',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['SHARE'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'CUSTOMER',
    identityRequired: true,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },
  {
    key: 'realized_cash.counterparty.outflow.supplier.share',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['OUTFLOW'],
    dimensions: ['COUNTERPARTY'],
    periodKinds: ['MONTH', 'YTD', 'YEAR'],
    comparisonChildKinds: null,
    operations: ['SHARE'],
    allowedFilters: ['partyProfile'],
    requiredFilters: ['partyProfile'],
    requiredPartyProfile: 'SUPPLIER',
    identityRequired: true,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCounterparty',
    sourceToolOrSurface: 'counterparty_identity_quality',
  },

  // --- cash_cost_center_* (MONTH only hoje) ---
  {
    key: 'realized_cash.cost_center.month.ranking_winner',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['COST_CENTER'],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['RANKING_WINNER'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: 1,
    defaultLimit: 1,
    executorKey: 'realizedCashCostCenter',
    sourceToolOrSurface: 'cash_cost_center_ranking',
  },
  {
    key: 'realized_cash.cost_center.month.ranking_topn',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['COST_CENTER'],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['RANKING_TOPN'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCostCenter',
    sourceToolOrSurface: 'cash_cost_center_ranking',
  },
  {
    key: 'realized_cash.cost_center.month.lookup',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['COST_CENTER'],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['LOOKUP'],
    allowedFilters: ['costCenterQuery'],
    requiredFilters: ['costCenterQuery'],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCostCenter',
    sourceToolOrSurface: 'cash_cost_center_lookup',
  },
  {
    key: 'cash_result.cost_center.month.lookup',
    metric: 'CASH_RESULT',
    semanticFamily: 'FLOW',
    directions: ['NET'],
    dimensions: ['COST_CENTER'],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['LOOKUP'],
    allowedFilters: ['costCenterQuery'],
    requiredFilters: ['costCenterQuery'],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCostCenter',
    sourceToolOrSurface: 'cash_result_cost_center_lookup',
  },
  {
    key: 'realized_cash.cost_center.compare.month_pair',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['COST_CENTER'],
    periodKinds: ['COMPARISON'],
    comparisonChildKinds: ['MONTH'],
    operations: ['COMPARE'],
    allowedFilters: ['costCenterQuery'],
    requiredFilters: ['costCenterQuery'],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'realizedCashCostCenter',
    sourceToolOrSurface: 'compare_cash_cost_center',
  },
  {
    key: 'realized_cash.cost_center.month.movements',
    metric: 'REALIZED_CASH',
    semanticFamily: 'FLOW',
    directions: ['INFLOW', 'OUTFLOW'],
    dimensions: ['COST_CENTER'],
    periodKinds: ['MONTH'],
    comparisonChildKinds: null,
    operations: ['MOVEMENTS'],
    allowedFilters: ['costCenterQuery'],
    requiredFilters: ['costCenterQuery'],
    identityRequired: false,
    maxLimit: DRILL_MAX,
    defaultLimit: DRILL_DEFAULT,
    executorKey: 'realizedCashCostCenter',
    sourceToolOrSurface: 'cash_cost_center_movement_lines',
  },

  // --- current_financial_snapshot (preload) ---
  {
    key: 'receivable_stock.current.value',
    metric: 'RECEIVABLE_STOCK',
    semanticFamily: 'STOCK',
    directions: null,
    dimensions: [null],
    periodKinds: ['CURRENT'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'currentSnapshot',
    sourceToolOrSurface: 'current_financial_snapshot',
  },
  {
    key: 'payable_stock.current.value',
    metric: 'PAYABLE_STOCK',
    semanticFamily: 'STOCK',
    directions: null,
    dimensions: [null],
    periodKinds: ['CURRENT'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'currentSnapshot',
    sourceToolOrSurface: 'current_financial_snapshot',
  },
  {
    key: 'delinquency.current.value',
    metric: 'DELINQUENCY',
    semanticFamily: 'STOCK',
    directions: null,
    dimensions: [null],
    periodKinds: ['CURRENT'],
    comparisonChildKinds: null,
    operations: ['VALUE'],
    allowedFilters: [],
    requiredFilters: [],
    identityRequired: false,
    maxLimit: null,
    defaultLimit: null,
    executorKey: 'currentSnapshot',
    sourceToolOrSurface: 'current_financial_snapshot',
  },
] as const;

const BY_KEY = new Map(
  ANALYTICAL_CAPABILITY_REGISTRY.map((capability) => [capability.key, capability] as const),
);

export function listAnalyticalCapabilities(): readonly AnalyticalCapability[] {
  return ANALYTICAL_CAPABILITY_REGISTRY;
}

export function getAnalyticalCapability(
  key: string,
): AnalyticalCapability | undefined {
  return BY_KEY.get(key);
}
